aic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('manyatta.urls', namespace='manyatta')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

manyatta/urls.py
from django.urls import path
from . import views

app_name = 'manyatta'

urlpatterns = [
    # ping mailchimp
    path('ping/', views.mailchimp_ping_view, name='ping'),

    path('', views.index, name='index'),

    path('search/', views.search, name='search'),

    path('subscribe', views.subscribe_view, name='subscribe'),

    path('success/', views.subscribe_success_view, name='subscribe_success'),

    path('fail/', views.subscribe_fail_view, name='subscribe_fail'),

    path('unsubscribe/', views.unsubscribe_view, name='unsubscribe'),

    path('unsubscribe/success/', views.unsubscribe_success_view, name='unsubscribe_success'),

    path('unsubscribe/fail/', views.unsubscribe_fail_view, name='unsubscribe_fail'),

    path('about/', views.about, name='about'),

    path('sermon_list/', views.sermon_list, name='sermon_list'),

    path('<int:year>/<int:month>/<int:day>/<slug:sermon>/', views.sermon_detail, name='sermon_detail'),

    path('contact_us/', views.contact_us, name='contact_us'),

    path('mens-ministry/', views.men, name='mens-ministry'),

    path('womens-ministry/', views.women, name='womens-ministry'),

    path('sundayschool-ministry/', views.sunday_school, name='sundayschool-ministry'),

    path('youth-ministry/', views.youth, name='youth-ministry'),

    path('praisenworship-ministry/', views.praise_worship, name='praisenworship-ministry'),

    path('news_events_list/', views.NewsEventList.as_view(), name='news_events_list'),

    path('<slug:slug>/', views.NewsEventDetail.as_view(), name='news_events_detail'),

    

    # path('news_events_list/', views.news_events_list, name='news_events_list'),
    #
    # path('<int:year>/<int:month>/<int:day>/<slug:news_event>/', views.news_events_detail, name='news_events_detail'),

]

manyatta/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Sermon(models.Model):
    STATUS_CHOICES = (
        ('draft', 'draft'),
        ('publish', 'publish')
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    feature_img = models.ImageField(blank=True, null=True, upload_to='feature_img')
    preacher = models.CharField(max_length=50)
    readings = models.CharField(max_length=200)
    content = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('manyatta:sermon_detail', args=[self.publish.year,
                                                       self.publish.month,
                                                       self.publish.day,
                                                       self.slug])


class NewsEvent(models.Model):
    STATUS_CHOICES = (
        ('draft', 'draft'),
        ('publish', 'publish')
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    feature_img = models.ImageField(blank=True, null=True, upload_to='feature_img')
    content = RichTextUploadingField()
    organizer = models.CharField(max_length=200, blank=True, null=True)
    commence_date = models.DateTimeField(blank=True, null=True)
    ending_date = models.DateTimeField(blank=True, null=True)
    entry_fee = models.DecimalField(decimal_places=0, max_digits=5, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('manyatta:news_events_detail', args=[self.publish.year,
    #                                                         self.publish.month,
    #                                                         self.publish.day,
    #                                                         self.slug])

manyatta/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()


class EmailForm(forms.Form):
    email = forms.EmailField()


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

manyatta/views.py
import hashlib
import logging
from django.conf import settings
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView

from .models import Sermon, NewsEvent
from .forms import EmailForm, ContactForm

from mailchimp_marketing import Client
from mailchimp_marketing.api_client import ApiClientError

logger = logging.getLogger(__name__)

mailchimp = Client()
mailchimp.set_config({
    'api_key': settings.MAILCHIMP_API_KEY,
    'server': settings.MAILCHIMP_REGION,
})


# Create your views here.
# view used to check if there is successful connection between mailchimp and the app
def mailchimp_ping_view(request):
    response = mailchimp.ping.get()
    return JsonResponse(response)


def subscribe_view(request):
    if request.method == 'POST':
        email = request.POST['subscriber_email']
        try:
            form_email = email

            # member info contains the user information that will be stored in mailchimp
            member_info = {
                'email_address': form_email,
                'status': 'subscribed',
            }
            response = mailchimp.lists.add_list_member(
                settings.MAILCHIMP_MARKETING_AUDIENCE_ID,
                member_info)
            logger.info(f'API call successful: {response}')
            return redirect('manyatta:subscribe_success')

        except ApiClientError as error:
            logger.error(f'An exception occurred: {error.text}')
            return redirect('manyatta:subscribe_fail')


def index(request):
    return render(request, 'index.html')


def subscribe_success_view(request):
    return render(request, 'message.html', {
        'title': 'Successfully subscribed',
        'message': 'Yay, you have been successfully subscribed to our mailing list.',
        'unsubscribe-link': ''
    })


def subscribe_fail_view(request):
    return render(request, 'message.html', {
        'title': 'Failed to subscribe',
        'message': 'Oops, something went wrong.',
    })


def unsubscribe_view(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            try:
                form_email = form.cleaned_data['email']
                # hashing the user's email using md5 to generate a subscriber hash will allow to manipulate the
                # user's data
                form_email_hash = hashlib.md5(form_email.encode('utf-8').lower()).hexdigest()

                # member_update used to change the user data
                member_update = {
                    'status': 'unsubscribed',
                }
                response = mailchimp.lists.update_list_member(
                    settings.MAILCHIMP_MARKETING_AUDIENCE_ID,
                    form_email_hash,
                    member_update,
                )
                logger.info(f'API call successful: {response}')
                return redirect('manyatta:unsubscribe_success')

            except ApiClientError as error:
                logger.error(f'An exception occurred: {error.text}')
                return redirect('manyatta:unsubscribe_fail')

    return render(request, 'unsubscribe.html', {
        'form': EmailForm(),
    })


def unsubscribe_success_view(request):
    return render(request, 'message.html', {
        'title': 'Successfully unsubscribed',
        'message': 'You have been successfully unsubscribed from our mailing list.',
    })


def unsubscribe_fail_view(request):
    return render(request, 'message.html', {
        'title': 'Failed to unsubscribe',
        'message': 'Oops, something went wrong.',
    })


def about(request):
    return render(request, 'about.html')


def sermon_list(request):
    sermons = Sermon.objects.filter(status='publish').order_by('-publish')

    p = Paginator(sermons, 6)  # paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return the last page
        page_obj = p.page(p.num_pages)

    return render(request, 'sermonlist.html', {'sermons': page_obj})


def sermon_detail(request, year, month, day, sermon):
    sermon = get_object_or_404(Sermon, slug=sermon,
                               status='publish',
                               publish__year=year,
                               publish__month=month,
                               publish__day=day)

    return render(request, 'sermon_detail.html', {'sermon': sermon})


class NewsEventList(ListView):
    queryset = NewsEvent.objects.filter(status='publish').order_by('-publish')
    template_name = 'newsneventslist.html'
    paginate_by = 6


# def news_events_list(request):
#     news_events = NewsEvent.objects.filter(status='publish').order_by('-publish')
#     paginator = Paginator(news_events, 6)  # Show 25 contacts per page.
#
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#
#     return render(request, 'newsneventslist.html', {'news_events': news_events,
#                                                     'page_obj': page_obj})


class NewsEventDetail(DetailView):
    model = NewsEvent
    template_name = 'newsnevents_detail.html'


# def news_events_detail(request, year, month, day, news_event):
#     news_event = get_object_or_404(NewsEvent, slug=news_event,
#                                    status='publish',
#                                    publish__year=year,
#                                    publish__month=month,
#                                    publish__day=day)
#     return render(request, 'newsnevents_detail.html', {'news_event': news_event})


def contact_us(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        form_data = {
            'name': name,
            'email': email,
            'message': message,
        }
        message = '''
            From:\n\t\t{}\n
            Message:\n\t\t{}\n
            Email:\n\t\t{}\n
            '''.format(form_data['name'], form_data['message'], form_data['email'],)
        send_mail('You got a mail!', message, '', ['jumaanton98@gmail.com'])
        messages.success(request, 'Your email has been sent successfully. We will reach out to you as soon as possible')
        return render(request, 'contact.html')

    else:
        return render(request, 'contact.html', {})


def search(request):
    if request.method == 'GET':
        query = request.GET['search_query']
        search_results = Sermon.objects.filter(status='publish').annotate(
            search=SearchVector('title', 'content'), ).filter(search=query)

    return render(request, 'search.html', {'query': query,
                                           'search_results': search_results, })


def men(request):
    return render(request, 'menministry.html')


def women(request):
    return render(request, 'womenministry.html')


def sunday_school(request):
    return render(request, 'sundayschoolministry.html')


def youth(request):
    return render(request, 'youthministry.html')


def praise_worship(request):
    return render(request, 'praisenworship.html')

manyatta/templates/about.html
{% extends 'base.html' %} 
{% load static %}
{% block title %} About Us {% endblock %}

{% block content %}

    <!-- header -->
    <div class="about-header position-relative">
        <h1 class="header-text text-light position-absolute top-50 start-50 translate-middle">About Us</h1>
    </div>


    <div class="about-cont row mt-2 container-fluid justify-content-center">
        <div class="col-lg-4 col-md-12 col-sm-10">
            <img src="{% static 'images/pastor.png' %}" class="img-fluid mt-lg-5 pt-lg-5 mt-md-5 pt-md-5" alt="pastor">
        </div>

        <div class="col-lg-8 col-md-12 col-sm-10">
            <h3 class="text-danger fw-bold">
                About Us
            </h3>

            <h4 class="fw-bold text-start">Brief History</h4>
            <p class="text-start">
                AIC Manyatta Local Church Foundation Stone was laid by Bishop Rev. Simeoon Otiende on 20th October 2010 and officially dedicated to God on 16th April 2017 by Rev. Philip O. Osenya. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Rem voluptatum
                aperiam sit, blanditiis mollitia natus, explicabo aspernatur quasi quo molestiae quod ea quia modi porro. Nisi ipsa ipsum ab tempora.
                <br> <br> Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet aspernatur corporis obcaecati. Nihil, consequuntur aspernatur alias sunt, perspiciatis veritatis expedita tempora mollitia quia nostrum, repudiandae modi nisi
                vero nulla vitae!
            </p>

            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-4 col-sm-12">

                    <img src="{% static 'images/mission.png' %}" alt="mission img" class="mx-auto d-block">
                    <h3 class="text-danger fw-bold mt-2"> Our Mission</h3>

                    <figure class="text-center">
                        <blockquote class="blockquote">
                            <p>To prepare God's people for works of service through vibrant worship, intimate fellowship, effective service and transforming witness.</p>
                        </blockquote>
                        <figcaption class="blockquote-footer">
                            Ephesians <cite title="Source Title">4:12</cite>
                        </figcaption>
                    </figure>

                </div>

                <div class="col-lg-4 col-md-4 col-sm-12">
                    <img src="{% static 'images/value.png' %}" alt="value img" class="mx-auto d-block">

                    <h3 class="text-danger fw-bold mt-2"> Our Core Value</h3>

                    <figure class="text-center">
                        <blockquote class="blockquote">
                            <p>Love</p>
                        </blockquote>
                    </figure>

                </div>

                <div class="col-lg-4 col-md-4 col-sm-12">
                    <img src="{% static 'images/vision.png' %}" alt="vision img" class="mx-auto d-block">

                    <h3 class="text-danger fw-bold mt-2"> Our Vision</h3>

                    <figure class="text-center">
                        <blockquote class="blockquote">
                            <p>To be a church where believers in Christ are at peace with God and man.</p>
                        </blockquote>
                    </figure>
                </div>
            </div>
        </div>
    </div>


    <!-- Our Pastors -->
    <div class="row justify-content-around container mt-4 gx-5 mx-auto">

        <h3 class="text-danger text-center fw-bold mb-5">
            Our Pastors
        </h3>

        <div class="col-lg-4 col-md-4 col-sm-10 mb-5">

            <div class="card pastor-cont border-0 hvr-curl-bottom-right hvr-grow" style="width: 18rem;">
                <img src="{% static 'images/pastor.png' %}" alt="" class="card-img-top mt-3 border-1 border-bottom-0 border-top border-start border-end border-danger rounded-top">

                <div class="card-body bg-dark text-light rounded-bottom">
                    <h5 class="card-title fw-bolder text-danger">Juma Antony</h5>
                    <p class="card-text">Pastor in Charge</p>
                </div>
            </div>

        </div>

        <div class="col-lg-4 col-md-4 col-sm-10 mb-5">

            <div class="card pastor-cont border-0 hvr-curl-bottom-right hvr-grow" style="width: 18rem;">
                <img src="{% static 'images/pastor.png' %}" alt="" class="card-img-top mt-3 border-1 border-bottom-0 border-top border-start border-end border-danger rounded-top">

                <div class="card-body bg-dark text-light rounded-bottom">
                    <h5 class="card-title fw-bolder text-danger">Juma Antony</h5>
                    <p class="card-text">Assistant Pastor </p>
                </div>
            </div>

        </div>

    </div>

    {% include 'ministry-programs.html' %}
       
{% endblock %}

manyatta/templates/home_latest_news_event.html
{% load static %}

{% for news_event in latest_news_event %}
      <!-- single news&event -->
      <div class="col-lg-4 col-md-4 col-10 mt-3">
        <div class="card w-100 news-event-cont border-0" data-aos="zoom-in-up" data-aos-duration="1000">
            <img src="{% if news_event.feature_img %}{{ news_event.feature_img.url }}{% else %}{% static 'images/no_img.png' %}{% endif %}" class="card-img-top img news-event-img " alt="sermon feature img">

            <div class=" card-body text-center news-event-body-cont bg-light hvr-float">
                <div class="calender-clock text-start bg-danger p-1 rounded fw-bold text-light">
                    <i class="fa-solid fa-calendar-days"></i>&nbsp &nbsp {{ news_event.publish }}
                </div>
                <h4 class="card-title mt-3">
                    <a href="{% url 'manyatta:news_events_detail' news_event.slug %}" class="text-decoration-none text-capitalize sermon-title fw-bold" target="_blank" rel="noopener noreferrer">
                        {{ news_event.title }}
                    </a>
                </h4>

                <p class="card-text text-start">
                    {% autoescape off %}
                        {{ news_event.content|capfirst|linebreaks| truncatechars:80 }}
                    {% endautoescape %}
                </p>
                <a href="{% url 'manyatta:news_events_detail' news_event.slug %}" class="btn btn-danger btn-md btn-outline-dark border-0 fw-bold">
                    Learn More
                </a>
            </div>

        </div>
    </div>
{% empty %}
<div class="col">
    There are no Sermons at the Momment. Check in Later
</div
{% endfor %}
          

manyatta/templates/home_latest_sermons.html
{% load static %}

{% for sermon in latest_sermons %}
    <!-- single sermon-->
    <div class="col-lg-3 col-md-4 col-10 mt-3">
        <div class="card w-100 sermon-cont" data-aos="fade-up" data-aos-duration="1000">
            <img src="{% if sermon.feature_img %}{{ sermon.feature_img.url }}{% else %}{% static 'images/no_img.png' %}{% endif %}" class="card-img-top img hvr-shrink" alt="sermon feature img">
            <div class=" card-body text-center">
                <h4 class="card-title">
                    <a href="{{ sermon.get_absolute_url }}" class="text-decoration-none text-capitalize sermon-title fw-bold" target="_blank" rel="noopener noreferrer">
                        {{ sermon.title }}
                    </a>
                </h4>
                <p class="card-text">
                    <i class="fa-solid fa-user text-danger"></i>&nbsp
                    <span class="fw-bold fst-italic">{{ sermon.preacher }}</span><br>

                    <i class="fa-solid fa-book-bible text-danger"></i>&nbsp
                    <span class="fw-bold fst-italic">{{ sermon.readings }}</span><br>

                    <i class="fa-solid fa-clock text-danger"></i>&nbsp
                    <span class="fw-bold fst-italic">{{ sermon.publish|date}}</span> <br>

                </p>
                <a href="{{ sermon.get_absolute_url }}" class="btn btn-danger btn-md btn-outline-dark border-0 fw-bold">
                    Learn More
                </a>
            </div>
        </div>
    </div>
{% empty %}
    <div class="col">
        There are no Sermons at the Momment. Check in Later
    </div
{% endfor %}

manyatta/templates/latest_news_event.html
{% load static %}

{% for news_event in latest_news_event %}
        <!-- single news & events -->
    <div class="d-flex mb-2">
        <div class="side-bar-date-cont fw-bold text-light bg-danger rounded fs-4 text-wrap" style="width:60px; height: 65px; padding-bottom: 5px;">
            {{ news_event.publish|date:"M d" }}
        </div>&nbsp;

        <a href="{% url 'manyatta:news_events_detail' news_event.slug %}" class="text-decoration-none text-capitalize fw-bold sermon-side-bar-link pt-1 my-3">
            {{news_event.title}}
        </a>
    </div>
{% empty %}

    <h5 class="fw-bold"> There are no news or events at the momment. Check in Later</h5>

{% endfor %}

manyatta/templates/ministry-programs.html
{% load static %}
<!-- Ministries -->

<h6 class="fw-bold text-danger mt-4">MINISTRIES</h6>
<h1 class="fw-bolder">Our Ministries</h1>

<h5 class="text-center fw-bold">Find A place where you belong, a place where you can serve or be served</h5>

<div class="container-fluid my-slider d-flex justify-content-center p-1">

    <!-- Men ministry -->
    <div class="ministry text-center px-lg-5 px-3">
        <div class="ministry-cont rounded pb-2">
            <div class="mb-3 position-relative">

                <a class="d-block" href="{% url 'manyatta:mens-ministry' %}">
                    <!-- Product Image -->
                    <img class="w-100 h-100 rounded-top" src="{% static 'images/men.png' %}" alt="youth image">
                </a>

                <div class="ministry-overlay">
                    <a href="{% url 'manyatta:mens-ministry' %}" class="btn btn-md btn-dark btn-outline-light fw-bold"> Learn More</a>
                </div>
            </div>

            <div class="bg-highlight">
                <h6>
                    <!-- Product title -->
                    <a href="{% url 'manyatta:mens-ministry' %}" class="text-decoration-none ministry-title fw-bold mb-2">
                        Men's Ministry
                    </a>
                </h6>
            </div>

        </div>
    </div>


    <!-- Women ministry -->
    <div class="ministry text-center px-lg-5 px-3">
        <div class="ministry-cont rounded pb-2">
            <div class="mb-3 position-relative">

                <a class="d-block" href="{% url 'manyatta:womens-ministry' %}">
                    <!-- Product Image -->
                    <img class="w-100 h-100 rounded-top" src="{% static 'images/women.png' %}" alt="youth image">
                </a>

                <div class="ministry-overlay">
                    <a href="{% url 'manyatta:womens-ministry' %}" class="btn btn-md btn-dark btn-outline-light fw-bold"> Learn More</a>
                </div>
            </div>

            <div class="bg-highlight">
                <h6>
                    <!-- Product title -->
                    <a href="{% url 'manyatta:womens-ministry' %}" class="text-decoration-none ministry-title fw-bold mb-2">
                        Women's Ministry
                    </a>
                </h6>
            </div>

        </div>
    </div>

    <!-- Youth ministry -->
    <div class="ministry text-center px-lg-5 px-3">
        <div class="ministry-cont rounded pb-2">
            <div class="mb-3 position-relative">

                <a class="d-block" href="{% url 'manyatta:youth-ministry' %}">
                    <!-- Product Image -->
                    <img class="w-100 h-100rounded-top" src="{% static 'images/youth.png' %}" alt="youth image">
                </a>

                <div class="ministry-overlay">
                    <a href="{% url 'manyatta:youth-ministry' %}" class="btn btn-md btn-dark btn-outline-light fw-bold"> Learn More</a>
                </div>
            </div>

            <div class="bg-highlight">
                <h6>
                    <!-- Product title -->
                    <a href="{% url 'manyatta:youth-ministry' %}" class="text-decoration-none ministry-title fw-bold mb-2">
                        Youth's Ministry
                    </a>
                </h6>
            </div>

        </div>
    </div>


    <!-- praisenworship-->
    <div class="ministry text-center px-lg-5 px-3">
        <div class="ministry-cont rounded pb-2">
            <div class="mb-3 position-relative">

                <a class="d-block" href="{% url 'manyatta:praisenworship-ministry' %}">
                    <!-- Product Image -->
                    <img class="w-100 h-100 rounded-top" src="{% static 'images/praisenworship.png' %}" alt="youth image">
                </a>

                <div class="ministry-overlay">
                    <a href="{% url 'manyatta:praisenworship-ministry' %}" class="btn btn-md btn-dark btn-outline-light fw-bold"> Learn More</a>
                </div>
            </div>

            <div class="bg-highlight">
                <h6>
                    <!-- Product title -->
                    <a href="{% url 'manyatta:praisenworship-ministry' %}" class="text-decoration-none ministry-title fw-bold mb-2">
                        Praise & Worship Ministry
                    </a>
                </h6>
            </div>

        </div>
    </div>

    <!-- Sunday School-->
    <div class="ministry text-center px-lg-5 px-3">
        <div class="ministry-cont rounded pb-2">
            <div class="mb-3 position-relative">

                <a class="d-block" href="{% url 'manyatta:sundayschool-ministry' %}">
                    <!-- Product Image -->
                    <img class="w-100 h-100 rounded-top" src="{% static 'images/sundayschool.png' %}" alt="youth image">
                </a>

                <div class="ministry-overlay">
                    <a href="{% url 'manyatta:sundayschool-ministry' %}" class="btn btn-md btn-dark btn-outline-light fw-bold"> Learn More</a>
                </div>
            </div>

            <div class="bg-highlight">
                <h6>
                    <!-- Product title -->
                    <a href="{% url 'manyatta:sundayschool-ministry' %}" class="text-decoration-none ministry-title fw-bold mb-2">
                        Sunday School Ministry
                    </a>
                </h6>
            </div>

        </div>
    </div>


</div>

<div id="controls">
    <div class="text-center">
        <i class="auto d-none text-light"></i>
        <i class="btn btn-outline-0 previous fa fa-chevron-left p-2 text-danger" aria-hidden="true"></i>
        <i class="btn btn-outline-0 next fa fa-chevron-right p-2 text-danger" aria-hidden="true"></i>
    </div>
</div>

<!-- Programs -->
<div class="programs container-fluid mt-3 mb-2">

    <div class="program-cont justify-content-center row p-2">
        <div class="col-lg-5 col-md-5 col-12 mt-4">
            <h3 class="text-light fw-bold">
                Join Us Every Sunday to Worship and Fellowship Together
            </h3>

            <img src="{% static 'images/pastor1.png' %}" class="rounded-circle program-img" alt="program img">

        </div>

        <div class="col-lg-5 col-md-5 col-12 mt-3">

            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                            <i class="fa-solid fa-church"></i>&nbsp Main Service
                        </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body fw-bold">
                            First Service - 07:00 Am - 09:00 Am <br><br> Second Service - 09:30 Am - 11:30 Am
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingTwo">
                        <button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                            <i class="fa-solid fa-person-praying"></i>&nbsp Wednesday Fellowship  
                        </button>
                    </h2>
                    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body fw-bold">Wednesday Fellowship- 5:00 Pm - 6:00 Pm</div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingThree">
                        <button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                            <i class="fa-solid fa-hands-holding-child"></i>&nbsp Sunday School
                        </button>
                    </h2>
                    <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body fw-bold">Sunday 07:00 Am - 09:00 Am</div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingFour">
                        <button class="accordion-button collapsed fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
                            <i class="fa-solid fa-children"></i>&nbsp Youth
                        </button>
                    </h2>
                    <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body fw-bold">Sunday 12:00 - 2:00 Pm</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>